In [2]:
import numpy as np

In [10]:
def homogenize(p: np.array):
    return np.append(p, 1)

def dehomogenize(p: np.array):
    return (p / p[-1])[:-1]

def get_translation_matrix(tau: np.array = np.zeros((3, 1)), C: np.array = np.identity(3)):
    a = np.concatenate((C, np.zeros((1,3))))
    t = np.reshape(np.expand_dims(np.append(tau, 1), axis=0), (4, 1))
    return np.concatenate((a, t), axis=1)

def get_intrinsic_param_matrix(f: float):
    return np.array([[f, 0, 0, 0], [0, f, 0, 0], [0, 0, 1, 0]])

In [4]:
# Page 46
o_c = np.array([20, 0, 10])
p_c = np.array([100, -2, 5])
p_c_h = homogenize(p_c)
T_c_w = get_translation_matrix(tau=o_c)
p_w_h = T_c_w @ p_c_h
p_w = dehomogenize(p_w_h)
print(p_w)

[120.  -2.  15.]


In [5]:
# Page 50
C_w_c = np.array([[1, 0, 0], [0, 0.707, 0.707], [0, -0.707, 0.707]])
p_w = np.array([10, -5, 100])
p_w_h = homogenize(p_w)
T_w_c = get_translation_matrix(C=C_w_c)
p_c_h = T_w_c @ p_w_h
p_c = dehomogenize(p_c_h)
print(p_c)

[10.    67.165 74.235]


In [8]:
# Page 53
o_c = np.array([20, 0, 10])
p_w = np.array([10, -5, 100])
p_w_h = homogenize(p_w)
C_w_c = np.array([[1, 0, 0], [0, 0.707, 0.707], [0, -0.707, 0.707]])
T_w_c = get_translation_matrix(tau=-C_w_c @ o_c, C=C_w_c)
p_c_h = T_w_c @ p_w_h
p_c = dehomogenize(p_c_h)
print(p_c)

[-10.     60.095  67.165]


In [11]:
# Page 56
p_c = np.array([-10, 20, 100])
p_c_h = homogenize(p_c)
Z = get_intrinsic_param_matrix(0.5)
q_h = Z @ p_c_h
q = dehomogenize(q_h)
print(q)

[-0.05  0.1 ]
